name: Deploy to Maven Central Repository

on:
  workflow_dispatch:

jobs:
  check_version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4 # checkout current branch
      - uses: actions/checkout@v4 # checkout master
        with:
          ref: master
          path: master-branch
      - name: check version install npm modules
        run: cd ./.github/scripts/check_version && npm install
      - name: check version
        run: node ./.github/scripts/check_version/main.js

  deploy:
    needs: check_version
    runs-on: ubuntu-20.04
    env:
      MAVEN_REPOSITORY_USERNAME: ${{ secrets.MAVEN_REPOSITORY_USERNAME }}
      MAVEN_REPOSITORY_PASSWORD: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
      MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
      MAVEN_GPG_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Deploy
        run: ./gradlew publish --no-daemon
