name: Deploy to Maven Central Repository

on:
  push:
    branches: [ 'release-*' ]

env:
  MAVEN_REPOSITORY_USERNAME: ${{ secrets.MAVEN_REPOSITORY_USERNAME }}
  MAVEN_REPOSITORY_PASSWORD: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
  MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
  MAVEN_GPG_KEY_ID: ${{ secrets.MAVEN_GPG_KEY_ID }}
  MAVEN_GPG_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_KEY_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Deploy
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: publish --no-daemon
