name: Java CI with Gradle

on:
  pull_request:
    branches-ignore: [ 'release-*' ]
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: build --no-daemon
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-report
          path: server/build/reports
          retention-days: 1