name: Java CI with Gradle

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: build --no-daemon
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-report
          path: server/build/reports
          retention-days: 1

  check_version:
    if: false # disabled for now
#    if: ${{ github.ref_name != 'master' }}
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # checkout current branch
      - uses: actions/checkout@v3 # checkout master
        with:
          ref: master
          path: master-branch
      - name: check version install npm modules
        run: cd ./.github/scripts/check_version && npm install
      - name: check version
        run: node ./.github/scripts/check_version/main.js
